title: TRPG
description: 현재 테스트 단계입니다
show_downloads: false
google_analytics:
remote_theme: pages-themes/hacker@v0.2.0
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
plugins:
  - jekyll-remote-theme
  - jekyll-feed
